services:
  app:
    build:
      context: .
      args:
        INSTALL_PROD_DEPS: ${INSTALL_PROD_DEPS:-1}
    ports:
      - "80:8000"
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    restart: unless-stopped
